Main svc
flykeeperB/java-explore-with-me pull request #4
Opened 2023-10-27 06:58 UTC by flykeeperB

2023-10-28 18:17 UTC, alexache requested changes

2023-10-28 18:17 UTC, alexache commented on main-service/src/main/java/ru/practicum/ewm/event/controller/publ/PublicEventController.java
> +        return eventService.getEvents(text, categories, paid, start, end, onlyAvailable, sort, from, size, request);
Можно передавать не весь объект запроса, а только нужные поля - айпи и URI

2023-10-28 18:17 UTC, alexache commented on main-service/src/main/java/ru/practicum/ewm/event/dto/EventDto.java
> +    LocalDateTime createdOn;
Потерялся модификатор доступа

2023-10-28 18:17 UTC, alexache commented on main-service/src/main/java/ru/practicum/ewm/stats/Stats.java
> +public class Stats {
Не очень говорящее название, StatsHelper?

2023-10-28 18:17 UTC, alexache commented on main-service/src/main/java/ru/practicum/ewm/event/service/impl/EventServiceImpl.java
> +                event.setConfirmedRequests(requestRepository.countAllByEventIdAndStatus(event.getId(),
Это запрос к базе в цикле, нужно получить сразу по списку событий, а не внутри цикла проходить

2023-10-28 18:17 UTC, alexache commented on main-service/src/main/java/ru/practicum/ewm/event/service/impl/EventServiceImpl.java
> +        if (event.getParticipantLimit() != 0 && event.getParticipantLimit() <= (confirmedRequests)) {
А если в запросе в данном методе не подтверждение, а реджект?

2023-10-28 18:17 UTC, alexache commented on main-service/src/main/java/ru/practicum/ewm/event/service/impl/EventServiceImpl.java
> +        eventRepository.save(event);
А что изменилось в событии?

2023-10-28 18:17 UTC, alexache commented on main-service/src/main/java/ru/practicum/ewm/event/service/impl/EventServiceImpl.java
> +                .map(stats::setViewsNumber).collect(Collectors.toList());
Не стоит обращаться к стороннему сервису в цикле, есть возможность делать сразу для списка URI

2023-10-28 19:49 UTC, flykeeperB commented on main-service/src/main/java/ru/practicum/ewm/event/controller/publ/PublicEventController.java
> +        return eventService.getEvents(text, categories, paid, start, end, onlyAvailable, sort, from, size, request);
Также подправил аналогичные соседние методы.

2023-10-29 17:45 UTC, alexache approved these changes

2023-10-29 18:07 UTC, merged